# Generated by Django 6.0.7 on 2026-08-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('system', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('gray', 'Gray'), ('titanium', 'Titanium'), ('blue', 'Blue'), ('dark blue', 'Dark Blue'), ('red', 'Red'), ('dark red', 'Dark Red')], max_length=50)),
                ('body_situation', models.CharField(choices=[('clean', 'Clean'), ('partial painted', 'Partial Painted'), ('painted', 'Painted'), ('paintless dent repair', 'Paintless Dent Repair'), ('body repair', 'Body Repair'), ('replaced', 'Replaced')], max_length=50)),
                ('description', models.TextField(default='null')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.cars')),
            ],
        ),
    ]
